// Generated by https://quicktype.io

export interface DoubanSearchItem {
    href:     string;
    target:   Target;
    children: Children;
}

export interface Children {
    key:    null;
    ref:    null;
    props:  Props;
    _owner: null;
}

export interface Props {
    data: Data;
}

export interface Data {
    comment:            Comment;
    rating:             Rating;
    vendor_count:       number;
    playable_date:      null | string;
    pic:                Pic;
    honor_infos:        HonorInfo[];
    vendor_icons:       string[];
    year:               string;
    card_subtitle:      string;
    id:                 string;
    title:              string;
    tags:               Tag[];
    interest:           null;
    type:               ItemType;
    alg_json:           string;
    has_linewatch:      boolean;
    photos:             string[];
    card:               Card;
    playable_date_info: PlayableDateInfo;
    following_rating:   null;
    uri:                string;
    episodes_info:      string;
    item_type:          ItemType;
}

export enum Card {
    Subject = "subject",
}

export interface Comment {
    comment: string;
    id:      string;
    user:    User;
}

export interface User {
    kind:    Kind;
    name:    string;
    url:     string;
    uri:     string;
    avatar:  string;
    is_club: boolean;
    type:    Kind;
    id:      string;
    uid:     string;
}

export enum Kind {
    User = "user",
}

export interface HonorInfo {
    kind:  ItemType;
    uri:   string;
    rank:  number;
    title: string;
}

export enum ItemType {
    Movie = "movie",
}

export interface Pic {
    large:  string;
    normal: string;
}

export enum PlayableDateInfo {
    Empty = "",
    The10天前上架 = "10天前上架",
    The4天前上架 = "4天前上架",
    The6天前上架 = "6天前上架",
    The7天前上架 = "7天前上架",
    The8天前上架 = "8天前上架",
    The9天前上架 = "9天前上架",
}

export interface Rating {
    count:      number;
    max:        number;
    star_count: number;
    value:      number;
}

export interface Tag {
    name: string;
    uri:  string;
}

export enum Target {
    Blank = "_blank",
}
